config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("recruitment.urls")),
    path("admin/", admin.site.urls),
]

recruitment/urls.py
from django.urls import path

from . import views

app_name = "recruitment"
urlpatterns = [
    path("", views.index),
    path("screenings/", views.show_screenings, name="show_screenings"),
    path("screenings/<uuid:id>", views.show_screening, name="show_screening"),
    path(
        "screenings/<uuid:id>/add_next_interview",
        views.add_next_interview_screening,
        name="add_next_interview_screening",
    ),
    path("screenings/apply", views.apply_screening, name="apply_screening"),
    path(
        "screenings/start_from_pre_interview",
        views.start_from_pre_interview_screening,
        name="start_from_pre_interview_screening",
    ),
]

recruitment/models.py
from uuid import uuid4

from django.db import models


class RecruiterRDB(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name


class ScreeningRDB(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    apply_date = models.DateField()
    status = models.SmallIntegerField()
    applicant_email_address = models.EmailField()

    def __str__(self) -> str:
        return self.applicant_email_address


class InterviewRDB(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    screening = models.ForeignKey(ScreeningRDB, on_delete=models.CASCADE)
    interview_date = models.DateField()
    interview_number = models.IntegerField()
    screening_step_result = models.SmallIntegerField()
    recruiter = models.ForeignKey(RecruiterRDB, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.interview_date.strftime("%Y/%m/%d")

recruitment/views.py
from datetime import datetime, date
from uuid import UUID

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

from .application_services import (
    ScreeningApplicationService,
    RecruiterApplicationService,
)


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "recruitment/index.html")


def show_screenings(request: HttpRequest) -> HttpResponse:
    screening_application_service = ScreeningApplicationService()
    screenings = screening_application_service.get_all_screenings()
    context = {"screenings": screenings}
    return render(request, "recruitment/screenings.html", context=context)


def show_screening(request: HttpRequest, id: UUID) -> HttpResponse:
    screening_application_service = ScreeningApplicationService()
    screening = screening_application_service.get_screening(id)
    context = {"screening": screening}
    return render(request, "recruitment/screening.html", context=context)


def add_next_interview_screening(request: HttpRequest, id: UUID) -> HttpResponse:
    screening_application_service = ScreeningApplicationService()
    recruiter_application_service = RecruiterApplicationService()
    if request.method == "GET":
        screening = screening_application_service.get_screening(id)
        recruiters = recruiter_application_service.get_all_recruiters()
        context = {"screening": screening, "recruiters": recruiters}
        return render(
            request, "recruitment/add_next_interview_screening.html", context=context
        )
    elif request.method == "POST":
        interview_date_str: str = request.POST["interview_date"]
        tdatetime = datetime.strptime(interview_date_str, "%Y-%m-%d")
        interview_date: date = date(tdatetime.year, tdatetime.month, tdatetime.day)
        recruiter_id: str = request.POST["recruiter_id"]
        screening_application_service.add_next_interview(
            screening_id=id,
            interview_date=interview_date,
            recruiter_id=UUID(recruiter_id),
        )
        return redirect("recruitment:show_screening", id=id)
    raise Exception("想定外のHTTPリクエストメソッドです。")


def apply_screening(request: HttpRequest) -> HttpResponse:
    screening_application_service = ScreeningApplicationService()
    if request.method == "GET":
        return render(request, "recruitment/apply_screening.html")
    elif request.method == "POST":
        applicant_email_address = request.POST.get("applicant_email_address")
        screening_application_service.apply(
            applicant_email_address=applicant_email_address
        )
        return redirect("recruitment:show_screenings")
    raise Exception("想定外のHTTPリクエストメソッドです。")


def start_from_pre_interview_screening(request: HttpRequest) -> HttpResponse:
    screening_application_service = ScreeningApplicationService()
    if request.method == "GET":
        return render(request, "recruitment/start_from_pre_interview_screening.html")
    elif request.method == "POST":
        applicant_email_address = request.POST.get("applicant_email_address")
        screening_application_service.start_from_pre_interview(
            applicant_email_address=applicant_email_address
        )
        return redirect("recruitment:show_screenings")
    raise Exception("想定外のHTTPリクエストメソッドです。")

recruitment/templates/recruitment/add_next_interview_screening.html
<h1>add_next_interview_screening.html</h1>
<h2>応募者: {{ screening.applicant_email_address }}</h2>
<p>応募日: {{ screening.apply_date }}</p>
<p>ステータス: {{ screening.status }}</p>
<p>次回面談/面接日: {{ screening.interviews.get_latest_interview.interview_date }}</p>
<p>前回の面談/面接結果: {{ screening.interviews.get_latest_interview.screening_step_result }}</p>

<form action="" method="post">
  {% csrf_token %}
  <div>
    <label for="interview_date">次回面談/面接日</label>
    <input type="date" id="interview_date" name="interview_date">
  </div>
  <div>
    <label for="recruiter_id">採用担当者</label>
    <select name="recruiter_id" size="12">
    {% for recruiter in recruiters %}
        <option value="{{ recruiter.recruiter_id.get_value }}">{{ recruiter.name }}</option>
    {% endfor %}
    </select>
  </div>
  <button type="submit">送信</button>
</form>

recruitment/templates/recruitment/apply_screening.html
<h1>apply_screenings.html</h1>
<form action="" method="post">
  {% csrf_token %}
  <div>
    <label for="applicant_email_address">メールアドレス</label>
    <input type="mail" id="applicant_email_address" name="applicant_email_address" required>
  </div>
  <button type="submit">送信</button>
</form>

recruitment/templates/recruitment/index.html
<h1>index.html</h1>
<p>hello world</p>

recruitment/templates/recruitment/screening.html
<h1>screenings.html</h1>
<h2>応募者: {{ screening.applicant_email_address }}</h2>
<p>応募日: {{ screening.apply_date }}</p>
<p>ステータス: {{ screening.status }}</p>
<p>次回面談/面接日: {{ screening.interviews.get_latest_interview.interview_date }}</p>
<p>前回の面談/面接結果: {{ screening.interviews.get_latest_interview.screening_step_result }}</p>

<a href="{% url 'recruitment:add_next_interview_screening' screening.screening_id.get_value %}">次の面談/面接の設定</a>

<a href="{% url 'recruitment:apply_screening' %}">採用選考の追加（面接から）</a>
<a href="{% url 'recruitment:start_from_pre_interview_screening' %}">採用選考の追加（面談から）</a>

recruitment/templates/recruitment/screenings.html
<h1>screenings.html</h1>
{% for screening in screenings %}
<h2>応募者: {{ screening.applicant_email_address }}</h2>
<p>応募日: {{ screening.apply_date }}</p>
<p>ステータス: {{ screening.status }}</p>
<p>次回面談/面接日: {{ screening.interviews.get_latest_interview.interview_date }}</p>
<p>前回の面談/面接結果: {{ screening.interviews.get_latest_interview.screening_step_result }}</p>
{% endfor %}

<a href="{% url 'recruitment:apply_screening' %}">採用選考の追加</a>

recruitment/templates/recruitment/start_from_pre_interview_screening.html
<h1>start_from_pre_interview_screening.html</h1>
<form action="" method="post">
  {% csrf_token %}
  <div>
    <label for="applicant_email_address">メールアドレス</label>
    <input type="mail" id="applicant_email_address" name="applicant_email_address" required>
  </div>
  <button type="submit">送信</button>
</form>